### ISSUE TITLE
[feat]: Create a header including logo, search bar and user card component.

### ISSUE THREAD

**Issue by purnasth** [Seven-Musketeers/frontend#6]
## Prerequisites

- [ ] vite + react
- [ ] react-router-dom 
- [ ] tailwindCSS

## Is your feature request related to a problem? Please describe.
- Creating a first component for the Leapblog web app.

### For ( lg || xl < ) devices
1. Logo for desktop devices at the left side of the screen.
2. Search Bar at the center.
3. User Profile at the right side of the screen.

### For mobile devices.
1. Include hamburger toggle button to the left side of the header followed by logo for mobile devices.
2. Similar with Search Bar and User Profile component.

## Additional context

1. On Click of logo make the website redirect to the home page.
2. Make the navbar sticky.
3. Initially make the bg-clr of header to transparent then use filter blur to the bg on scroll.

## Color Palettes:
- [ ] bg-clr: #021a24,
- [ ] root-green-clr: #00cb5b,
- [ ] root-yellow-clr: #ffb001,
- [ ] light-green-clr: #1b5045,
- [ ] blue-clr: #0049df,
- [ ] red-clr: #f14d2a,
- [ ] white-clr: #E1F7EB,
