### ISSUE TITLE
[feat]: Create a SideNav component.

### ISSUE THREAD

**Issue by purnasth** [Seven-Musketeers/frontend#8]
## Prerequisites

- [x] vite + react
- [x] tailwindCSS

## Is your feature request related to a problem? Please describe.
1. Creating a SideNav component associated with the header component.
2. Include the following urls on link component.
- Home
- Batch with sublist [ LSPs 2022, 2023, 2024 ...]
- Settings
- Report
- Help
- Send feedback
- copyright and goodwill at bottom.

### For ( lg || xl < ) devices
1. Make the SideNav active by default.

### For mobile devices.
1. Make the SideNav toggle button and opens/closes when toggled.

## Additional context

1. Make the color of the active link to: bg-color to bg-gray-700 and text-root-yellow-clr.
2. Add icons.

## Color Palettes:
- [ ] bg-clr: #021a24,
- [ ] root-green-clr: #00cb5b,
- [ ] root-yellow-clr: #ffb001,
- [ ] light-green-clr: #1b5045,
- [ ] blue-clr: #0049df,
- [ ] red-clr: #f14d2a,
- [ ] white-clr: #E1F7EB,

## Figma Design from @astikagrg 

![image](https://github.com/Seven-Musketeers/frontend/assets/107195487/44928c88-5f37-4c65-b788-e4982ec4471e)
