### ISSUE TITLE
[feat]: Create a bottom navbar for mobile devices.

### ISSUE THREAD

**Issue by purnasth** [Seven-Musketeers/frontend#9]
## Prerequisites

- [x] vite + react
- [x] tailwindCSS
- [x] styled-component
- [x] react-router-dom
- [x] pseudo-elements

### For ( lg || xl < ) devices
1. Make the Navbar disabled by default.

### For mobile devices.
1. Make the bottom navbar responsive and interactive with necessary links.

## Additional context

1. Only display icons and display title when hover or when active.
2. Make the active color to root-yellow-clr.
3. Add an animation of active & hover slider.

## Color Palettes:
- [ ] bg-clr: #021a24,
- [ ] root-green-clr: #00cb5b,
- [ ] root-yellow-clr: #ffb001,
- [ ] light-green-clr: #1b5045,
- [ ] blue-clr: #0049df,
- [ ] red-clr: #f14d2a,
- [ ] white-clr: #E1F7EB,

## Figma Design from @astikagrg 

![image](https://github.com/Seven-Musketeers/frontend/assets/107195487/3bcd26e1-2280-4ce9-8c2b-970585bcf2d6)
